### ISSUE TITLE
link containers with ambassador pattern

### ISSUE THREAD

**Issue by missedone** [grammarly/rocker-compose#12]
Hi folks

rocker-compose is really interesting to me, when play around with it, i'm wondering do you have plan or ever think about to support linking containers with ambassador pattern.

relate articles:
* [SERVICE DISCOVERY FOR DOCKER CONTAINERS USING CONSUL AND REGISTRATOR](http://www.livewyer.com/blog/2015/02/05/service-discovery-docker-containers-using-consul-and-registrator)
* [Automatic container registration with Consul and Registrator](http://jlordiales.me/2015/02/03/registrator/)

in brief, i think we can extend current rocker-compose containers linking mechanism, for example, in the yaml file:
```
web:
    image: tomcat
    net: ambassador:db
db:
    image: postgres
```

then, rocker-compose will start db first, and inject DB relate properties (e.g. domain, port, user, passwd, etc.) into the 'web' container as ENV variables when start it, similar as what link does.

this approach, however, will have external dependencies including a running consul container and registrator container before launch the service via `rocker-compose run`.

**Comment by ybogdanov** [comment]
Hi @missedone,

Not sure I understood you correctly. But there is [`net: container:<id|name>`](https://github.com/grammarly/rocker-compose#network-share) network mode that allows you to share network between the containers and rocker-compose respects the dependencies here.

The problem with external dependencies though is that when you run your `compose.yml`, in case of missing dependencies (e.g. consul-agent), you don't have a specification to run them. We struggled with this problem for some time. Later we decided to use [loose coupling approach](https://github.com/grammarly/rocker-compose#loose-coupling-network), where an application and "agents" can live without each other, but be able to talk if needed. This way, we run two different `compose.yml` specs on the server independently, one for platform stuff (same for all servers), another for the higher level apps. Another option is to describe all agents in the `compose.yml` of your app, which most of the times, not what you want.

**Comment by missedone** [comment]
hi @ybogdanov 
> docker link provides a good starting point for networking construction. Communication between containers on the same host is fairly straight-forward and communication between hosts can occur over regular public networks as long as the ports are mapped correctly and the connection information is given to the other party.

(quoted from [The Docker Ecosystem: Networking and Communication](https://www.digitalocean.com/community/tutorials/the-docker-ecosystem-networking-and-communication))

so in case of cross multi-host networking, one approach is use ambassador pattern (aka, Service Discovery in diagram below):
![Discover](https://assets.digitalocean.com/articles/docker_ecosystem/Discover-Flow.png)

one concrete implementation of ambassador pattern works quite great for me is use the combination of [Consul](https://www.consul.io) and [Registrator](https://github.com/gliderlabs/registrator):
* Registrator listening on the docker daemon, if new container started, it registers the container info (including exposed ports, ip address, or environment variables defined in Dockerfile, etc.) into the Key-Value store Consul
* Consul, beside of it's feature as a central Key-Value store, it also provide DNS service

for example, we have two container, WEB and DB, while WEB depends on DB, when DB started, it's ip, consul generated domain name, port this sort of info are registered into Consul, when WEB start, it query from Consul about the DB hostname, port etc, and update the web app's configuration file (like jdbc url, etc.)

so from so good, but i think with Rocker-compose, we can abstract this service discovery process into framework level rather than inject the non-app relate logic into the container bootstrap.

at Rocker-compose side, we can extend the link mechanism, when rocker-compose start the WEB container, it queries the hostname and port on-behalf of the container, and inject the properties as ENV vars to the WEB container, while the WEB container startup script only need to read the ENV var to update the configuration file, this way, we can nicely decouple the container startup with the service discovery process.

regards to your concern: 
> in case of missing dependencies (e.g. consul-agent), you don't have a specification to run them.

i think we can make rocker-compose configurable, and make the specs of Consul and Registrator as global level specs if ambassador link mode is enabled, every time before Rocker-compose run the application spec, it will run these global level specs (aka. Consul and Registrator) first to make sure the service is ready for subsequence container processing.

what do you think?
thanks

**Comment by ctrlok** [comment]
Hi @missedone
We also have been thinking a lot about how to deal with multi-instance service relations and service discovery with consul and registrator. And more importantly, what is the role of `rocker-compose` here. There are tools like [Ansible](http://www.ansible.com/) and [Terraform](https://terraform.io/) (and many more), which can do a lower-level orchestration. While `rocker-compose` is a higher-level provisioner, that handles delivery of containers.
Anyway, if you want to bootstrap instances with registrator and consul, you can do something like this:
```yaml
# server1
namespace: db
containers: 
  main:
    image: db_image
    env: SERVICE_CHECK_SCRIPT=/health/bin/check
# server2
namespace: web
containers:
  main:
    image: web
    env: SERVICE_80_CHECK_HTTP=/health/endpoint/path
    wait_for: check_db
  check_db:
    image: consul_check
    state: ran
    cmd: /check_service_in_consul db.db_image
```

**Comment by ybogdanov** [comment]
> at Rocker-compose side, we can extend the link mechanism, when rocker-compose start the WEB container, it queries the hostname and port on-behalf of the container, and inject the properties as ENV vars to the WEB container, while the WEB container startup script only need to read the ENV var to update the configuration file, this way, we can nicely decouple the container startup with the service discovery process.

1. What if the database is not available when we start the WEB container?
2. What if the database is moved after the WEB container started?

> i think we can make rocker-compose configurable, and make the specs of Consul and Registrator as global level specs if ambassador link mode is enabled, every time before Rocker-compose run the application spec, it will run these global level specs (aka. Consul and Registrator) first to make sure the service is ready for subsequence container processing.

We have been also thinking about it recently. But decided to decouple the "platform" layer from the "app" one. These are two separate `compose.yml` manifests that are managed separately. "App" layer can run without "platform" though we always provision "platform" first. We don't link across different manifests, but rather use [loose coupling techniques](https://github.com/grammarly/rocker-compose#loose-coupling-network). Tomorrow we will publish the blog post about this, by the way.

And finally, I recommend you to read [this article](http://ferd.ca/it-s-about-the-guarantees.html), which I believe is a great philosophy regarding software dependencies. To be short, your WEB app should be able to boot without DB even exist and be able to catch up once DB becomes available. Consul and registrator provide good functionality to achieve this.
