### ISSUE TITLE
Provide ARM binary

### ISSUE THREAD

**Issue by marvinroger** [grammarly/rocker-compose#27]
Since more and more cloud providers now provide cheap ARM-based servers (e.g. Scaleway), it would be great if you could provide an ARM binary for rocker. 

Docker doesn't officially support ARM, but the fact is it is commonly used on this architecture (see Hypriot for example). The Docker Hub also contains some arm images (see armbuild).

**Comment by ybogdanov** [comment]
Hi @marvinroger,

`rocker` and `rocker-compose` are just clients and are designed to be used on local machines or CI servers. We don't have any of these installed on our production servers. Although, if you can't run Docker, there is almost no sense in running rocker/rocker-compose on a machine, unless you want to use this machine as an "executor". Can you give a more concrete use case?

**Comment by marvinroger** [comment]
I can't use docker-machine because there is no driver available for Scaleway. So yes, my idea was to to trigger rocker-compose from the CI on the production server directly. But reading the CLI reference more in depth, there is no need to use docker-machine, we can provide connection args directly.

Sorry for the noise!
