### ISSUE TITLE
"keep_volumes: true" not respected unless present during initial run

### ISSUE THREAD

**Issue by tomxtobin** [grammarly/rocker-compose#40]
If `keep_volumes: true` is added to an existing container's definition after it has been started with `rocker-compose run`, it isn't respected upon running `rocker-compose rm`. The container's volumes are removed even if `rocker-compose run` was immediately run again after adding the `keep_volumes: true` property.

The reverse case works as expected, though: if `keep_volumes: true` was originally present in the container's definition upon `rocker-compose run`, and is removed from the definition before `rocker-compose rm`, the container's volumes are properly removed.

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker-compose/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
