### ISSUE TITLE
Suitability as an init system?

### ISSUE THREAD

**Issue by Matthias247** [grammarly/rocker-compose#44]
Hi,
first of this is more a question than an issue, but as it probably interests more people I'm asking here nevertheless. Would you currently see that rocker-compose can be used as some kind of init system that can start me a set of containers depending on a local configuration file on system startup or are there any big issues or something else that I'm not aware of that would prevent this from your point of view?  
I'm currently working on a system where I want to start some containers on startup, which provide the main functionality. In case of updates I want to simply replace them by new containers that I import in my local repository and a new container configuration file. From the readme here and some first experiments rocker-compose would be very helpful here. I would simply start it with systemd on startup, and for updates I would replace the compose file which would then lead to new containers being loaded on the next startup and the old ones to be automatically deleted. Is there something that I'm missing or that I should be aware of? I found that that I probably need some kind of `stop` command for a clean system shutdown in addition to the currently available `rm` command, but otherwise it looks great.
Thanks!

**Comment by ybogdanov** [comment]
Thanks for your question and sorry this being unanswered. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker-compose/blob/master/README.md

Closing this issue for now.
