### ISSUE TITLE
"detachKeys" in .docker/config.json breaks rocker-compose

### ISSUE THREAD

**Issue by tomxtobin** [grammarly/rocker-compose#45]
If the new `detachKeys` option is present in one's `.docker/config.json` file, `rocker-compose run` breaks with the following error:

```
FATA[0000] json: cannot unmarshal string into Go value of type docker.dockerConfig 
```

I _think_ this is an upstream bug with [fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient) but I'm not well-versed enough in Go to say for sure.

This issue is present in rocker as well: grammarly/rocker#77

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker-compose/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
