### ISSUE TITLE
Support build and dockerfile properties for the container spec

### ISSUE THREAD

**Issue by erikwilson** [grammarly/rocker-compose#48]
Those properties are used heavily for my development environment. I would like to try out rocker-compose but would rather not work around lack of support for build and dockerfile.

**Comment by missedone** [comment]
were you seeking for the build tool: [Rocker](https://github.com/grammarly/rocker) ?

**Comment by erikwilson** [comment]
For rocker-compose files. This is a feature request as per instructions in
the README. Any others desiring those properties should comment.

**Comment by dikderoy** [comment]
definitely want that feature for same reason as @erikwilson in development, when making constant changes and relauching a hole bunch of containers it is really useful. i.e. then developing some kind of swarm based system (lead node + child nodes with different roles, all built from same code base).
Yes, I can workaround that with a bashscript, but for now `docker-compose build && docker-compose restart` is just simplier and easier to control

**Comment by sebglon** [comment]
same than @dikderoy

**Comment by aacebedo** [comment]
Same here !

**Comment by delaman** [comment]
I request this vital feature as well!

**Comment by ricardofbarros** [comment]
+1

**Comment by swordbeta** [comment]
Sadly we can't use `rocker-compose` without this vital feature

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker-compose/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
