### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by sergle** [grammarly/rocker-compose#59]
There are no updates for year, was it abandoned?

**Comment by ybogdanov** [comment]
Yep, it's abandoned. Sorry for that. Will post a disclaimer soon.

**Comment by francislavoie** [comment]
So, what about that disclaimer @ybogdanov ? Should update your README

**Comment by ybogdanov** [comment]
Sorry. Here it is https://github.com/grammarly/rocker-compose/blob/master/README.md
